# Generated by Django 3.1.2 on 2020-10-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0005_posts_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AlterField(
            model_name='posts',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
