# Generated by Django 3.1.2 on 2020-10-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0006_auto_20201031_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
