# Generated by Django 3.1.2 on 2020-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0007_auto_20201031_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
