# Generated by Django 3.1.2 on 2020-10-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0008_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
