# Generated by Django 3.1.2 on 2020-10-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0009_auto_20201031_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
