# Generated by Django 3.1.2 on 2020-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0011_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='files',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
    ]
