# Generated by Django 3.1.2 on 2020-10-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0014_auto_20201031_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
