# Generated by Django 3.1.2 on 2020-11-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0015_auto_20201031_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
