# Generated by Django 3.1.2 on 2020-11-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0016_auto_20201101_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
