# Generated by Django 3.1.2 on 2020-11-01 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0017_auto_20201101_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
    ]
