# Generated by Django 3.1.2 on 2020-11-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0018_auto_20201101_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
