# Generated by Django 3.1.2 on 2020-11-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0019_auto_20201101_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='video',
            field=models.FileField(default=1, upload_to='videos'),
            preserve_default=False,
        ),
    ]
